import subprocess
import sys
from pathlib import Path

import pytest

# Add the scripts directory to sys.path so we can import the validation function directly
SCRIPTS_DIR = Path(__file__).parent.parent / ".agents" / "scripts"
sys.path.append(str(SCRIPTS_DIR))

from validate_commit_message import validate_commit_message  # type: ignore # noqa: E402

SCRIPT_PATH = SCRIPTS_DIR / "validate_commit_message.py"


@pytest.mark.parametrize(
    "message",
    [
        "feat: add user authentication",
        "fix(login): resolve incorrect password error",
        "docs!: update readme with breaking changes",
        "refactor(db): rename migrations table",
        "ci: configure github actions pipeline",
        "perf(engine): optimize query response time\n\nMore details in the body.",
        "feat(api)!: drop support for v1 endpoints",
    ],
)
def test_valid_commit_messages(message: str):
    is_valid, error = validate_commit_message(message)
    assert is_valid, f"Expected valid commit message: {message}. Error: {error}"


@pytest.mark.parametrize(
    "message,expected_error",
    [
        (
            "added a new feature",
            "Error: Subject line does not follow Conventional Commits format.",
        ),
        (
            "invalidtype: some description",
            "Error: Invalid commit type 'invalidtype'.",
        ),
        (
            "feat : add space before colon",
            "Error: Subject line does not follow Conventional Commits format.",
        ),
        (
            "feat(auth) : add space before colon with scope",
            "Error: Subject line does not follow Conventional Commits format.",
        ),
        (
            "feat:",
            "Error: Subject line does not follow Conventional Commits format.",
        ),
        (
            "",
            "Error: Commit message is empty.",
        ),
        (
            "# just comments\n# in the message",
            "Error: Commit message is empty.",
        ),
        (
            "feat: " + "a" * 80,
            "Error: Subject line exceeds 72 characters",
        ),
    ],
)
def test_invalid_commit_messages(message: str, expected_error: str):
    is_valid, error = validate_commit_message(message)
    assert not is_valid
    assert expected_error in error


@pytest.mark.parametrize(
    "message",
    [
        "Merge branch 'main' of github.com:org/repo",
        "Merge pull request #123 from branch-name",
        "Merge remote-tracking branch 'origin/main'",
        'Revert "feat: add something"',
        "squash! feat: add something",
        "fixup! fix: some bug",
        "amend! docs: fix typo",
    ],
)
def test_ignored_commit_messages(message: str):
    # These are autogenerated by git and should be bypassed
    is_valid, error = validate_commit_message(message)
    assert is_valid, f"Expected ignored commit to be valid: {message}. Error: {error}"


def test_subprocess_validation_success(tmp_path: Path):
    commit_file = tmp_path / "COMMIT_EDITMSG"
    commit_file.write_text("feat(core): initialize project", encoding="utf-8")

    result = subprocess.run(
        [sys.executable, str(SCRIPT_PATH), str(commit_file)],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0
    assert result.stderr == ""


def test_subprocess_validation_failure(tmp_path: Path):
    commit_file = tmp_path / "COMMIT_EDITMSG"
    commit_file.write_text("fix login button", encoding="utf-8")

    result = subprocess.run(
        [sys.executable, str(SCRIPT_PATH), str(commit_file)],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 1
    assert "Error: Subject line does not follow Conventional Commits format." in result.stderr
