#!/usr/bin/env python3
import re
import sys
from pathlib import Path

# Constants for validation limits
MAX_SUBJECT_LENGTH = 72
MIN_ARGUMENTS = 2

# Conventional Commit Types
VALID_TYPES = {
    "feat",
    "fix",
    "docs",
    "style",
    "refactor",
    "test",
    "chore",
    "build",
    "ci",
    "perf",
    "revert",
}

# Regex to match conventional commits: type(scope)?: description
CONVENTIONAL_COMMIT_RE = re.compile(r"^([a-zA-Z0-9_-]+)(?:\(([a-zA-Z0-9_-]+)\))?(!?): (.+)$")

# Patterns to ignore (e.g., merge/squash/revert autogenerated commits)
IGNORE_PREFIXES = (
    "Merge branch",
    "Merge pull request",
    "Merge remote-tracking branch",
    'Revert "',
    "squash!",
    "fixup!",
    "amend!",
)


def validate_commit_message(message: str) -> tuple[bool, str]:
    """Validate a commit message.

    Returns:
        A tuple of (is_valid, error_message).
    """
    lines = [line.strip() for line in message.splitlines()]
    # Remove lines starting with '#' (git comments)
    non_comments = [line for line in lines if line and not line.startswith("#")]

    if not non_comments:
        return False, "Error: Commit message is empty."

    subject = non_comments[0]

    if subject.startswith(IGNORE_PREFIXES):
        return True, ""

    is_valid = False
    error_msg = ""

    if len(subject) > MAX_SUBJECT_LENGTH:
        error_msg = (
            f"Error: Subject line exceeds {MAX_SUBJECT_LENGTH} characters (got {len(subject)})."
        )
    else:
        match = CONVENTIONAL_COMMIT_RE.match(subject)
        if not match:
            error_msg = (
                f"Error: Subject line does not follow Conventional Commits format.\n"
                f"Subject: '{subject}'\n"
                f"Expected format: <type>(optional-scope)?: <description>\n"
                f"Example: feat(auth): add login form"
            )
        else:
            commit_type, _, _, description = match.groups()
            if commit_type not in VALID_TYPES:
                error_msg = (
                    f"Error: Invalid commit type '{commit_type}'.\n"
                    f"Must be one of: {', '.join(sorted(VALID_TYPES))}"
                )
            elif not description.strip():
                error_msg = "Error: Description cannot be empty."
            else:
                is_valid = True

    return is_valid, error_msg


def main():
    if len(sys.argv) < MIN_ARGUMENTS:
        print("Usage: validate_commit_message.py <commit-msg-file>")
        sys.exit(1)

    commit_msg_filepath = Path(sys.argv[1])
    if not commit_msg_filepath.exists():
        print(f"Error: Commit message file '{commit_msg_filepath}' does not exist.")
        sys.exit(1)

    try:
        content = commit_msg_filepath.read_text(encoding="utf-8")
    except Exception as e:
        print(f"Error reading commit message file: {e}")
        sys.exit(1)

    is_valid, error_msg = validate_commit_message(content)
    if not is_valid:
        print(error_msg, file=sys.stderr)
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()
