#!/usr/bin/env bash
set -euo pipefail

# Read from file if provided, otherwise from stdin
if [ $# -gt 0 ] && [ "$1" != "-" ]; then
    commit_msg=$(cat "$1")
else
    commit_msg=$(cat)
fi

# Trim leading/trailing whitespace
commit_msg=$(echo "$commit_msg" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

if [ -z "$commit_msg" ]; then
    echo "Error: Commit message is empty." >&2
    exit 1
fi

# Get the first line (subject line), ignoring leading comments or blank lines
subject_line=$(echo "$commit_msg" | grep -v '^[[:space:]]*#' | grep -v '^[[:space:]]*$' | head -n 1 || true)
subject_line=$(echo "$subject_line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

if [ -z "$subject_line" ]; then
    echo "Error: Commit message is empty." >&2
    exit 1
fi

# Strip GitHub PR suffix (e.g., " (#123)") from subject line if present
subject_line=$(echo "$subject_line" | sed -E 's/ \(#[0-9]+\)$//')

# Ignore git autogenerated merge / squash / revert commits
if [[ "$subject_line" =~ ^(Merge|Revert \"|squash\!|fixup\!|amend\!) ]]; then
    exit 0
fi

# Check subject length (max 72 characters)
if [ ${#subject_line} -gt 72 ]; then
    echo "Error: Subject line exceeds 72 characters (got ${#subject_line})." >&2
    exit 1
fi

# Regex pattern for Conventional Commits
pattern='^(feat|fix|docs|style|refactor|test|chore|build|ci|perf|revert)(\([a-zA-Z0-9_-]+\))?!?: .+$'

if [[ ! "$subject_line" =~ $pattern ]]; then
    echo "Error: Subject line does not follow Conventional Commits format." >&2
    echo "Subject: '$subject_line'" >&2
    echo "Expected format: <type>(optional-scope)?: <description>" >&2
    echo "Example: feat(auth): add login form" >&2
    exit 1
fi

# Extract the description and verify it's not empty
description_part=$(echo "$subject_line" | sed -E 's/^[^:]+: (.*)$/\1/' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

if [ -z "$description_part" ]; then
    echo "Error: Description cannot be empty." >&2
    exit 1
fi

exit 0
