agent:
  name: "demo_agent"
  model: "gemini-2.5-flash"
  provider: "google"
  system_prompt_path: "src/prompts/system_prompt.txt"
  user_prompt_path: "src/prompts/user_prompt.txt"
  app_data_dir: "data"
  streaming: false
  retry:
    attempts: 3
    delay: 5
  acceptable_data_types:
    - "image/png"
    - "image/jpeg"
    - "image/gif"
  max_image_width: 1024
  max_image_height: 1024
  min_image_width: 128
  min_image_height: 128
  acceptable_file_types:
    - "application/pdf"
    - "text/plain"
    - "text/markdown"
    - "text/html"
  max_file_size_bytes: 20971520  # 20 MB
  max_files_per_message: 5
  tools:
    - "search_vectordb"
    - "get_weather"
