tools:
  read_google_sheet:
    type: "google_sheet_read"
    config:
      spreadsheet_id: "1ZDWpuGhOs2vBxf4jpA7EjOr7U57B52n50-_p1qPevWE"
      credentials_path: null
  write_google_sheet:
    type: "google_sheet_write"
    config:
      spreadsheet_id: "1ZDWpuGhOs2vBxf4jpA7EjOr7U57B52n50-_p1qPevWE"
      credentials_path: null
  add_vocab_entry:
    type: "google_sheet_add_vocab_entry"
    config:
      spreadsheet_id: "1ZDWpuGhOs2vBxf4jpA7EjOr7U57B52n50-_p1qPevWE"
      credentials_path: null
